### ISSUE TITLE
beginDelayedTransition issue

### ISSUE THREAD

**Issue by andris95** [nickbutcher/plaid#134]
Hello world!
I have watched a video on YouTube from Google I/O 2016 about Material Design improvements and I decided to play a little with TransitionManager's beginDelayedTransition. So, it started well, but I got a strange bug both in my application and in "Plain": after beginDelayedTransition gets called, if I try to scroll the RecyclerView then strange things happen. The viewHolder's size is not correct. Sometimes the adapter scrolls to wrong position. Or neightbour items changes each others positions.
For more information see this StackOverflow post: http://stackoverflow.com/questions/40247448/begindelayedtransition-issue

![screenshot_20161025-214316](https://cloud.githubusercontent.com/assets/9825787/19701338/9f82c776-9b03-11e6-8078-ea7c8d48da5f.png)
![screenshot_20161025-214322](https://cloud.githubusercontent.com/assets/9825787/19701337/9f804e2e-9b03-11e6-8e06-5d7709190aa9.png)

**Comment by nickbutcher** [comment]
Indeed. Essentially `TransitionManager` sets up a bunch of animations then runs them. These do not take into account any changes to the views while they are running, so you can end up with this kind of artifact.

The ugly workaround i've used in Plaid is to prevent interaction while the (brief) transition runs:

https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/DribbbleShot.java#L446

**Comment by VeegaP** [comment]
@nickbutcher What is the state of the art solution to this problem? Is it to avoid using `TransitionManager.beginDelayedTransition` altogether? What should I use to animate expandable items inside a RecyclerView, while allowing scrolling?

**Comment by ataulm** [comment]
>What should I use to animate expandable items inside a RecyclerView, while allowing scrolling?

I think it's an either/or situation. When the user has decided to navigate to a different screen, the current screen shouldn't be interacted with. From the user's point of view:

- the transition should be fast enough that they are unable to interact with the current screen
- if they _do_ attempt to interact with the current screen, while it's in transition, it shouldn't result in glitches (i.e. block interaction)

A similar issue is discussed here with taps instead of scrolling - https://github.com/nickbutcher/plaid/issues/555

**Comment by curioustechizen** [comment]
@VeegaP Thanks for posting this update. It is really helpful.

There's one aspect that I still don't understand: If I read your `onHolderSelected` code correctly, it seems like you are applying a changeBounds transition on a RecyclerView rather than the individual item within it. How does that work?

**Comment by AndroidDrone** [comment]
Hello every one,

In my case Screen transition occurs only on iBall devices. when the user scrolls fast or double-tap on the item
is there any workaround to fix it.
