### ISSUE TITLE
How can i make a transparent status bar like yours?

### ISSUE THREAD

**Issue by Android74** [nickbutcher/plaid#167]
So im really struggling to make a status bar like yours (transparent and shows views under itself). I can't manage to show any view under my status bar like yours does (on home activity). Any help? I've seen the code but it didn't help much.

**Comment by nickbutcher** [comment]
Hi there, there are a few steps to drawing behind the status bar:

1. Make sure your `theme` [sets](https://github.com/nickbutcher/plaid/blob/master/app/src/main/res/values/styles.xml#L34) `android:windowDrawsSystemBarBackgrounds` to `true`.
2. [Set](https://github.com/nickbutcher/plaid/blob/master/app/src/main/res/values/styles.xml#L35) your status bar to a semi-opaque color.
3. [Set](https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/HomeActivity.java#L134) an appropriate system UI visibility i.e. ```view.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION);```

You layout will now extend behind behind the status bar. If you want to inset your content so that it is offset by the size of the system UI them take a look at `View#fitsSystemWindows` ([great article on this](https://medium.com/google-developers/why-would-i-want-to-fitssystemwindows-4e26d9ce1eec#.qiuq0no7b)) or [handle yourself in a inset listener](https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/HomeActivity.java#L191).

Hope that this helps!

**Comment by Android74** [comment]
Thank you so much!
