### ISSUE TITLE
Few issues in beta.

### ISSUE THREAD

**Issue by DonLiangGit** [nickbutcher/plaid#23]
Rotate Screen results:
1. Main Page reloading
2. Plaid Item Page loses the `Heart` button.

Main Page:
1. The suggest email visible faster than the login dialog after hitting the FAB button
2. Menu icon in toolbar not horizontal centered
3. 

Plaid Item Page:
1. Reply Edittext still focused after tapping other button
2. There is button hidden on the top right in toolbar in this page, not sure why not setting it gone
3. few other padding margin ui stuff

good job keep going

**Comment by nickbutcher** [comment]
Hi thanks for the detailed feedback; I really tried to sweat the details so appreciate this level of attention.

> Main Page reloading

Currently the app doesn't have any persistence, just reloads each time.  This is because it is a UI sample and I didn't want to delay / de-focus the project by adding this.  I may revisit in the future.

> Plaid Item Page loses the Heart button.

Fixed in 65330ed49ab436c89b3db9e4b5d68dfe7f886e1f

> The suggest email visible faster than the login dialog after hitting the FAB button

Fixed in 4e7466a529394b98459c7caa095e217b344116d6

> Menu icon in toolbar not horizontal centered

Do you mean the filter icon on the home screen.  This is default Toolbar behaviour so i'm loathe to deviate here.

> Reply Edittext still focused after tapping other button

It now blurs after focusing a comment. 5ea5a5665b0b803ce21f9a0f6d70f1a23abb1a43

> There is button hidden on the top right in toolbar in this page, not sure why not setting it gone

Not sure what you mean? The back arrow?  That is shown intentionally.

> few other padding margin ui stuff

Can you be more specific as i'd love to fix these!

**Comment by nickbutcher** [comment]
Closing this issue, please comment @DonLiangGit if you want to re-open any aspect?

**Comment by donlingliang** [comment]
Nick, I will review the app tonight since those comments were left one year ago.
