### ISSUE TITLE
Toolbar quick return 

### ISSUE THREAD

**Issue by tasomaniac** [nickbutcher/plaid#34]
I scrolled to bottom too much and wanted to do a search. I had to scroll back to the top to find the search button.

**Comment by nickbutcher** [comment]
I've toyed with this idea but think that you're likely in *either* feed browsing 'mode' or searching. It seems unlikely that you switch between these tasks. I also really like the simplicity of a static toolbar which emphasizes that content is literally the topmost entity.  For these reasons, i'm inclined not to add quick-return but I could be convinced otherwise.

**Comment by tasomaniac** [comment]
I was browsing. I scrolled really much. And one of the designs were really similar to something I remember vaguely. I had to search and find it. I found it eventually. Quick return would help me in this scenario. But in overall use case of the app, I am not sure.
