### ISSUE TITLE
[DN] Implement scraper for DN search

### ISSUE THREAD

**Issue by nickbutcher** [nickbutcher/plaid#436]

**Comment by ataulm** [comment]
✋

**Comment by ataulm** [comment]
I had a look at the search results for DN: it doesn't seem to contain as much info as Dribbble (we can extract story ID and title).

We can either:

- simplify the Story model used in the feed so that it only takes these two things (cost to code complexity) and have a separate model for the full Story or
- use the DN API to query the required values for each search result (cost to API rate limits and network requests) so we can construct the full Story object (it needs created date, user ID)

For me, I think the latter is more isolated (so easier to not mess up) but the former is correct.

A middle ground could be to make more fields in the Story model optional, and do another fetch when loading a story to fill in the gaps. What do you think?

**Comment by ataulm** [comment]
This is (in my understanding) blocked by #602 , should that be worked on first?
