### ISSUE TITLE
Reactive architecture 

### ISSUE THREAD

**Issue by sockeqwe** [nickbutcher/plaid#49]
Hi Nick, we have talked about the architecture of this app via hangouts a few weeks ago.

Finally, I was able to write down some of my thoughts on my blog. It was way more complex and tooked much longer than I have expected,  but I do not really need to tell you that :smile: 

If you are still interested in hearing my point of view about software architecture on android I would like to ask you to read my blog post about the refactoring as I'm explaining some core aspects there (so I don't have to repeat myself here again).

Part 1: http://hannesdorfmann.com/android/plaid-refactored-1/
Part 2: http://hannesdorfmann.com/android/plaid-refactored-2/

If you really want to go the "truly reactive way" as described in my blog post I will do some code clean up and make a pull request. Otherwise, I don't mind because as already said the main goal was to write an blog post.

All libraries I have used are under Apache 2 license. 

Last but not least I want to thank you for open sourcing this app. It's a truly inspiration and I have learned a lot about animations and UI / UX!

**Comment by nickbutcher** [comment]
Hi Hannes, I read and really enjoyed your blog posts.  Thanks for taking the time to create and share them.

I'm reluctant to merge these changes because, as you pointed out, I'd like to keep the repo as accessible as possible so that the most users can learn these UI techniques.  The goal of Plaid has never been to create the perfect app but to demonstrate UI concepts.  I would be worried that a more complex architecture (while obviously advantageous) would damage that goal.

I would however be more than happy to point people to your fork.  Let me know when you think it's in a good state & I'll update the readme.

**Comment by sockeqwe** [comment]
That makes perfect sense and I have already expected this.

However, I don't think that I will invest more time on my fork. 

Keep up you good work! Can't wait to install a final Plaid 1.0 version on my phone.

**Comment by Rainer-Lang** [comment]
@sockeqwe But your blog about Plaid and refactoring it isn't finished - hopefully?

**Comment by sockeqwe** [comment]
@Rainer-Lang I will write one last part about testing the refactored app
