### ISSUE TITLE
Cannot resolve all the R file

### ISSUE THREAD

**Issue by apm29** [nickbutcher/plaid#577]
Don't Know whether it's a Problem, I cannot resolve all the R file ,but I can still  run project on device well,

**Comment by ataulm** [comment]
If the project builds and runs, it's not a problem.

By "cannot resolve" does this mean that Android Studio complains? You could try File > Invalidate Caches and Restart.

I've been having an issue in the latest canaries where the files resolve fine, but going to a resource declaration (CMD+click/CMD+b) takes you to the generated R.java file rather than the XML resource.

**Comment by apm29** [comment]
thanks，it works well on lastest canary
