### ISSUE TITLE
BaselineGridTextView clips first line

### ISSUE THREAD

**Issue by krokyze** [nickbutcher/plaid#93]
Hey,

as you can see in screenshot first line is clipped. Is it some kind of padding issue?

![screen shot 2016-06-07 at 22 30 09](https://cloud.githubusercontent.com/assets/5682176/15871970/c7a389e2-2cff-11e6-866f-efbf47536dad.png)

**Comment by nickbutcher** [comment]
Hmm, this is likely due to turning off [`includeFontPadding`](https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/widget/BaselineGridTextView.java#L76). I can't quite remember why I did this, I think to simplify some of the font height calculations. Should definitely revisit this at some point.

**Comment by nickbutcher** [comment]
I _think_ that this issue is fixed by 12587b6a23a8654d51d9c2a394880fb894f031c0 (which should ship in build 0.9.7) but cannot repro. Can you confirm?

**Comment by hzsweers** [comment]
Cool, give it a shot later today

**Comment by krokyze** [comment]
Just checked. Everything works perfectly. Thanks.

**Comment by nickbutcher** [comment]
Awesome, thanks for verifying.

**Comment by hzsweers** [comment]
Sorry for the late response, checked on my end too and looks great!
